language: python
python:
    - "3.5"
before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y libav-tools
    - sudo apt-get install -y ubuntu-restricted-extras
install:
    - cp contrib/env-sample .env
    - pip install -q -r requirements.txt
script:
    python manage.py test
